# Generated by Django 2.2.3 on 2019-11-22 23:04

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_reportfindinglink_finding_guidance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='details',
            field=tinymce.models.HTMLField(blank=True, help_text='Provide a description for this finding that introduces it', null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='risk_determination',
            field=tinymce.models.HTMLField(blank=True, help_text='Describe the impact of this finding on the affected entities', null=True, verbose_name='Risk Determination'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='recommendation',
            field=tinymce.models.HTMLField(blank=True, help_text='Describe how this finding can be resolved or addressed', null=True, verbose_name='Recommendation'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='source',
            field=tinymce.models.HTMLField(blank=True, help_text='Describe sources used to identify finding', null=True, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='tools',
            field=tinymce.models.HTMLField(blank=True, help_text='Describe tools used to identify finding', null=True, verbose_name='Tools'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='references',
            field=tinymce.models.HTMLField(blank=True, help_text='Provide solid references for this finding, such as links to reference materials, tooling, and white papers', null=True, verbose_name='References'),
        ),
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ForeignKey(help_text='Select the project tied to this report', null=True, on_delete=django.db.models.deletion.CASCADE, to='rolodex.Project'),
        ),
    ]
