# Generated by Django 2.2.3 on 2020-07-09 18:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_tinymce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='recommendation',
            field=tinymce.models.HTMLField(blank=True, help_text='Provide a recommendation for how this finding can be resolved or addressed', null=True, verbose_name='Recommendation'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='source',
            field=tinymce.models.HTMLField(blank=True, help_text='Provide an explanation for how the finding was discovered', null=True, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='tools',
            field=tinymce.models.HTMLField(blank=True, help_text='List which tools were used to help identify the finding', null=True, verbose_name='tools'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='details',
            field=tinymce.models.HTMLField(blank=True, help_text='Provide a description for this finding that introduces it', null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='recommendation',
            field=tinymce.models.HTMLField(blank=True, help_text='Provide a recommendation for how this finding can be resolved or addressed', null=True, verbose_name='Recommendation'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='references',
            field=tinymce.models.HTMLField(blank=True, help_text='Provide solid references for this finding, such as links to reference materials, tooling, and white papers', null=True, verbose_name='References'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='risk_determination',
            field=tinymce.models.HTMLField(blank=True, help_text='Describe the impact of this finding on the affected entities', null=True, verbose_name='Risk Determination'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='source',
            field=tinymce.models.HTMLField(blank=True, help_text='Provide an explanation for how the finding was discovered', null=True, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='tools',
            field=tinymce.models.HTMLField(blank=True, help_text='List which tools were used to help identify the finding', null=True, verbose_name='tools'),
        ),
    ]
