# Generated by Django 2.2.3 on 2020-07-09 14:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_auto_20200110_0505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finding',
            name='description',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='finding_guidance',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='host_detection_techniques',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='impact',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='mitigation',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='network_detection_techniques',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='replication_steps',
        ),
        migrations.RemoveField(
            model_name='reportfindinglink',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reportfindinglink',
            name='host_detection_techniques',
        ),
        migrations.RemoveField(
            model_name='reportfindinglink',
            name='impact',
        ),
        migrations.RemoveField(
            model_name='reportfindinglink',
            name='mitigation',
        ),
        migrations.RemoveField(
            model_name='reportfindinglink',
            name='network_detection_techniques',
        ),
        migrations.RemoveField(
            model_name='reportfindinglink',
            name='replication_steps',
        ),
        migrations.AddField(
            model_name='finding',
            name='additional_guidance',
            field=models.TextField(blank=True, help_text='Provide notes for your team that describes how the finding is intended to be used and any details that should be provided during editing', null=True, verbose_name='Additional Guidance'),
        ),
        migrations.AddField(
            model_name='finding',
            name='details',
            field=tinymce.models.HTMLField(blank=True, help_text='Provide a description for this finding that introduces it', null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='finding',
            name='recommendation',
            field=tinymce.models.HTMLField(blank=True, help_text='Provide a recommendation for how this finding can be resolved or addressed', null=True, verbose_name='Recommendation'),
        ),
        migrations.AddField(
            model_name='finding',
            name='risk_determination',
            field=tinymce.models.HTMLField(blank=True, help_text='Describe the impact of this finding on the affected entities', null=True, verbose_name='Risk Determination'),
        ),
        migrations.AddField(
            model_name='finding',
            name='source',
            field=tinymce.models.HTMLField(blank=True, help_text='Provide an explanation for how the finding was discovered', null=True, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='finding',
            name='tools',
            field=tinymce.models.HTMLField(blank=True, help_text='List which tools were used to help identify the finding', null=True, verbose_name='tools'),
        ),
        migrations.AddField(
            model_name='reportfindinglink',
            name='details',
            field=tinymce.models.HTMLField(blank=True, help_text='Provide a description for this finding that introduces it', null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='reportfindinglink',
            name='recommendation',
            field=tinymce.models.HTMLField(blank=True, help_text='Provide a recommendation for how this finding can be resolved or addressed', null=True, verbose_name='Recommendation'),
        ),
        migrations.AddField(
            model_name='reportfindinglink',
            name='risk_determination',
            field=tinymce.models.HTMLField(blank=True, help_text='Describe the impact of this finding on the affected entities', null=True, verbose_name='Risk Determination'),
        ),
        migrations.AddField(
            model_name='reportfindinglink',
            name='source',
            field=tinymce.models.HTMLField(blank=True, help_text='Provide an explanation for how the finding was discovered', null=True, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='reportfindinglink',
            name='tools',
            field=tinymce.models.HTMLField(blank=True, help_text='List which tools were used to help identify the finding', null=True, verbose_name='tools'),
        ),
    ]
